---
- name: Install Apache
  hosts: databaseservers
  become: true
  ignore_errors: false
  gather_facts: true

  tasks:
    - name: Update the system
      yum:
        name: '*'
        state: latest
      tags:
        - update
    - name: Install httpd
      package:
        name: httpd
        state: present
      tags:
        - install

    - name: Start the httpd
      systemd:
        name: httpd
        state: started
        enabled: true
      tags:
        - deamon

    - name: Copy index file to target
      copy:
        src: index.html
        dest: /var/www/html/index.html
      tags:
        - file_copy
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      systemd:
        name: httpd
        state: restarted
