---
- name: Database Servers Configuration
  hosts: databaseservers
  become: yes
  ignore_errors: yes
  gather_facts: false

  tasks:
    - name: Install packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - finger
        - wget
        - httpd
        - ntp
