---
- name: Database Servers Configuration
  hosts: databaseservers
  become: yes
  ignore_errors: yes
  gather_facts: true

  tasks:
    - name: Check number of CPUs
      command: nproc
      register: nproc_output

    - name: Display the output
      debug:
        var: nproc_output


- name: Create file
  hosts: databaseservers
  become: yes

  tasks:
    - name: Create file
      file:
        path: /home/ec2-user/week3
        state: touch
        mode: '0644'
      register: file_output

    - name: Debug file creation result
      debug:
        var: file_output
